In [1]:
import pandas as pd 

In [2]:
import numpy as np

In [3]:
str1 = ['a','b','c','d','e'] 

In [4]:
data_1 = [10,20,30,40,50]

In [5]:
arr = np.array(data_1)

In [6]:
dict1 = {'a':1,'b':2,'c':3,'d':4,'e':5}

In [7]:
#print everything
print(str1)
print(data_1)
print(arr)
print(dict1)

['a', 'b', 'c', 'd', 'e']
[10, 20, 30, 40, 50]
[10 20 30 40 50]
{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}


In [8]:
#create a series out of a list data_1 with no index parameter passed to series
my_series1 = pd.Series(data = data_1)

In [9]:
print(my_series1)
print(type(my_series1))

0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.core.series.Series'>


In [10]:
#check the characteristics of created series
my_series1.shape

(5,)

In [11]:
#check the dimension of series - will always be 1
my_series1.ndim

1

In [12]:
#check the size
my_series1.size

5

In [13]:
#check the indexes range
my_series1.index

RangeIndex(start=0, stop=5, step=1)

In [14]:
#summary on the series elements
my_series1.describe()

count     5.000000
mean     30.000000
std      15.811388
min      10.000000
25%      20.000000
50%      30.000000
75%      40.000000
max      50.000000
dtype: float64

In [15]:
#datatype of series
my_series1.dtype

dtype('int64')

In [16]:
my_series1.max()

50

In [17]:
#create a series with "data " parameter from data_1 list and change the index parameter using "str1" list
str1 = ['a','b','c','d','e']
my_series2 = pd.Series(data=data_1,index=str1)
print(my_series2)

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [18]:
#check the characteristics of created series
print('shape of the series', my_series2.shape)
print('\n')
print('dimension of the series', my_series2.ndim)
print('\n')
print('size of the series', my_series2.size)
print('\n')
print('data type of contents in series', my_series2.dtype)
print('\n')
print('index ranges of the series', my_series2.index)
print('\n')
print('Summary stats of data in the series', my_series2.describe())
print('\n')
print('max and min values in a series', my_series2.max(),my_series2.min())
print('\n')
print('indexes of max and min values in a series', my_series2.idxmax(),my_series2.idxmin())

shape of the series (5,)


dimension of the series 1


size of the series 5


data type of contents in series int64


index ranges of the series Index(['a', 'b', 'c', 'd', 'e'], dtype='object')


Summary stats of data in the series count     5.000000
mean     30.000000
std      15.811388
min      10.000000
25%      20.000000
50%      30.000000
75%      40.000000
max      50.000000
dtype: float64


max and min values in a series 50 10


indexes of max and min values in a series e a


In [19]:
#retrieving data from a series without indexes
my_series2

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [20]:
#retrieving data using user defined indexes
my_series2['a']

10

In [21]:
#retrieving data using default keys
my_series2[0]

10

In [22]:
#retrieving using slice notation
my_series2[0:]

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [23]:
#retreiving first 3 elements in series using default indexes and slice notations
my_series2[0:3]

a    10
b    20
c    30
dtype: int64

In [24]:
#retreiving first 3 elements in series using user defined indexes and slice notations
my_series2['a':'c']

a    10
b    20
c    30
dtype: int64

In [25]:
#creating a series with numeric indexes

my_seriesx = pd.Series(data=data_1,index=[100,200,300,400,500])

In [26]:
my_seriesx

100    10
200    20
300    30
400    40
500    50
dtype: int64

In [27]:
my_seriesx[0:3]

100    10
200    20
300    30
dtype: int64

In [28]:
my_seriesx.loc[100:300]

100    10
200    20
300    30
dtype: int64

In [29]:
#Mutability of A Series
my_series2['a'] = 298

In [30]:
my_series2

a    298
b     20
c     30
d     40
e     50
dtype: int64

In [31]:
my_series2['a']

298

In [32]:
#another way of creating a series - no need to give data= , index=
my_series3 = pd.Series(data_1,str1)
print(my_series3)

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [33]:
#create a series from a tuple
#create my_tup
my_tup1 = ((1,2),('aa','bb'),(3,4),('cc','dd'),(70,80))
my_tup1_series = pd.Series(data=my_tup1,index=str1)
print(my_tup1_series)

a      (1, 2)
b    (aa, bb)
c      (3, 4)
d    (cc, dd)
e    (70, 80)
dtype: object


In [34]:
my_tup1 = ((1,2),('aa','bb'),(3,4),('cc','dd'),(50,60))
my_tup1_series1 = pd.Series(data=my_tup1,index=str1)
print(my_tup1_series1)

a      (1, 2)
b    (aa, bb)
c      (3, 4)
d    (cc, dd)
e    (50, 60)
dtype: object


In [35]:
arr

array([10, 20, 30, 40, 50])

In [36]:
#create a series by using numpy array and labeled index 
my_ser4 = pd.Series(data=arr,index=str1)
print(my_ser4)

a    10
b    20
c    30
d    40
e    50
dtype: int32


In [37]:
arr[0]

10

In [38]:
### creating sreies from numpy array without index parameter
my_ser5 = pd.Series(arr)
print(my_ser5)

0    10
1    20
2    30
3    40
4    50
dtype: int32


In [39]:
my_ser5[0] = 300

In [40]:
my_ser5

0    300
1     20
2     30
3     40
4     50
dtype: int32

In [41]:
#create a series from a dictionary
print(dict1)
mystr1 = ['python','R','java','c++','cobol']
print(mystr1)

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
['python', 'R', 'java', 'c++', 'cobol']


In [42]:
#create series from dictionary, without index= parameter
my_series_6 = pd.Series(data = dict1)
print(my_series_6)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [43]:
dict1

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}

In [44]:
dict1['a']

1

In [45]:
mystr1 = ['b','a','c','d','e']

In [46]:
#create a series with index= parameter and pass the list "mystr1" as index
my_series_7 = pd.Series(data=dict1,index=mystr1)
print(my_series_7)

b    2
a    1
c    3
d    4
e    5
dtype: int64


In [47]:
mystr2 = ['a','b','c','d','e']

In [48]:
#create a series with index= parameter and pass the list "mylabel" as index
my_series_8 = pd.Series(data=dict1,index=mystr2)
print(my_series_8)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [49]:
mystr1[4] = 'e'

In [50]:
mystr1

['b', 'a', 'c', 'd', 'e']

In [51]:
my_series_9 = pd.Series(data=dict1,index=mystr1)
print(my_series_9)

b    2
a    1
c    3
d    4
e    5
dtype: int64


In [52]:
#getting Data from Series
myseries_10 = pd.Series(data=[1,2,3,4,5],index=['dog','cat','cow','pig','monkey'])

In [53]:
print(myseries_10)

dog       1
cat       2
cow       3
pig       4
monkey    5
dtype: int64


In [54]:
#get the value 4
myseries_10['pig']

4

In [55]:
myseries_11 = pd.Series(data=[100,200,300,400,399,599,199],index=['indx1','indx2','indx3','indx4','indx5','indx6','indx7'])
print(myseries_11)

indx1    100
indx2    200
indx3    300
indx4    400
indx5    399
indx6    599
indx7    199
dtype: int64


In [56]:
myseries_11[0]

100

In [57]:
myseries_101 = pd.Series(data=[100,200,300,400,399,599,199],index=[1,2,3,4,5,6,7])
print(myseries_101)

1    100
2    200
3    300
4    400
5    399
6    599
7    199
dtype: int64


In [58]:
myseries_101[7]

199

In [59]:
myseries_101[1]

100

In [60]:
myseries_11['indx6']

599

In [61]:
myseries_11[5]

599

In [62]:
#create numpy array with country names
np_country = np.array(['china','india','senegal','tanzania','nigeria','costa rica','fiji','samoa','indonesia','germany'])

In [63]:
#create a series with np_country
series_country = pd.Series(data=np_country)
print(series_country)

0         china
1         india
2       senegal
3      tanzania
4       nigeria
5    costa rica
6          fiji
7         samoa
8     indonesia
9       germany
dtype: object


In [64]:
#create an array of labels
np_country_labels = np.array(['lab1','lab2','lab3','lab4','lab5','lab6','lab7','lab8','lab9','lab10'])

In [65]:
#create a new series with labels
series_country1 = pd.Series(data=np_country, index=np_country_labels)
print(series_country1)

lab1          china
lab2          india
lab3        senegal
lab4       tanzania
lab5        nigeria
lab6     costa rica
lab7           fiji
lab8          samoa
lab9      indonesia
lab10       germany
dtype: object


In [66]:
#alternate ways of accessing data from a series using .loc
print(series_country1.loc['lab1'])

china


In [67]:
print(series_country1['lab1'])

china


In [68]:
print(series_country1[0])

china


In [69]:
print(series_country1.iloc[0])

china


In [70]:
#SCALAR SERIES
series_scalar = pd.Series(data=400,index=['a','b','c','d'])
print(series_scalar)

a    400
b    400
c    400
d    400
dtype: int64


In [71]:
series_scalar1 = pd.Series(400,['a','b','c','d'])
print(series_scalar1)

a    400
b    400
c    400
d    400
dtype: int64


In [72]:
series_scalar = pd.Series(data=400,index=['a','b','c','d'])
print(series_scalar)

a    400
b    400
c    400
d    400
dtype: int64


In [73]:
myscalarlist = [100,800,911,499,501]
myscalarlistarr = np.array(myscalarlist)
print(myscalarlistarr)

[100 800 911 499 501]


In [74]:
#get all values greater than 500
myscalarlistarr[myscalarlistarr>500]

array([800, 911, 501])

In [75]:
series_scalar6 = pd.Series(data=myscalarlistarr[myscalarlistarr>500],index= ('scal1','scal2','scal3'))

In [76]:
print(series_scalar6)

scal1    800
scal2    911
scal3    501
dtype: int32


In [77]:
series_country1

lab1          china
lab2          india
lab3        senegal
lab4       tanzania
lab5        nigeria
lab6     costa rica
lab7           fiji
lab8          samoa
lab9      indonesia
lab10       germany
dtype: object

In [78]:
#slice notation in series
series_country1['lab1':'lab3'] 

lab1      china
lab2      india
lab3    senegal
dtype: object

In [79]:
### other way using .loc
series_country1.loc['lab1':'lab3']

lab1      china
lab2      india
lab3    senegal
dtype: object

In [80]:
 #typical slice notation for default indexes 
series_country1[0:3]

lab1      china
lab2      india
lab3    senegal
dtype: object

In [81]:
series_country1.iloc[0:3]

lab1      china
lab2      india
lab3    senegal
dtype: object

In [82]:
#extracting using comma notation
series_country1[['lab1','lab3']]

lab1      china
lab3    senegal
dtype: object

In [83]:
series_country1

lab1          china
lab2          india
lab3        senegal
lab4       tanzania
lab5        nigeria
lab6     costa rica
lab7           fiji
lab8          samoa
lab9      indonesia
lab10       germany
dtype: object

In [84]:
series_country1[['lab1','lab4']]

lab1       china
lab4    tanzania
dtype: object

In [85]:
series_country1[['lab5','lab7']]

lab5    nigeria
lab7       fiji
dtype: object

In [86]:
#operations in series (vectorized operations)
ser_1_vec = pd.Series([100,200,300,400,500],index=['i1','i2','i3','i4','i5'])

In [87]:
ser_2_vec = pd.Series([500,1000,3000,5000,8000],index=['i6','i7','i1','i2','i8'])

In [88]:
ser_3_vec = pd.Series([1000,2000,3000,400,500],index=['i1','i10','i13','i14','i15'])

In [89]:
#add 2 series
ser_1_vec + ser_2_vec

i1    3100.0
i2    5200.0
i3       NaN
i4       NaN
i5       NaN
i6       NaN
i7       NaN
i8       NaN
dtype: float64

In [90]:
ser_1_vec * ser_2_vec

i1     300000.0
i2    1000000.0
i3          NaN
i4          NaN
i5          NaN
i6          NaN
i7          NaN
i8          NaN
dtype: float64

In [91]:
ser_3_vec = pd.Series([99,299,399,499,9],index=['i1','i2','i3','i4','i5'])


In [92]:
ser_4_vec = pd.Series([101,10,20,50,11],index=['i1','i2','i3','i4','i5'])

In [93]:
ser_3_vec > ser_4_vec

i1    False
i2     True
i3     True
i4     True
i5    False
dtype: bool

In [94]:
ser_5_vec = pd.Series([99,299,399,499,9])
ser_6_vec = pd.Series([101,10,20,50,11])

In [95]:
ser_5_vec > ser_6_vec 

0    False
1     True
2     True
3     True
4    False
dtype: bool

In [96]:
(ser_3_vec ['i1'] > ser_4_vec['i2'] ) and (ser_3_vec['i3'] < ser_4_vec['i4'])

False

In [97]:
(ser_3_vec ['i1'] > ser_4_vec['i2'] ) or (ser_3_vec['i3'] < ser_4_vec['i4'])

True

In [98]:
(ser_3_vec ['i1'] > ser_4_vec['i2'] ) != (ser_3_vec['i3'] < ser_4_vec['i4'])

True

In [99]:
#Data Frames in Pandas
#Data Frame Basics

import numpy as np
import pandas as pd

In [100]:
#from numpy.random import randn
from numpy.random import randn

In [101]:
np.random.seed(101)

In [102]:
myrandom_data = randn(5,4)
print(myrandom_data)

[[ 2.70684984  0.62813271  0.90796945  0.50382575]
 [ 0.65111795 -0.31931804 -0.84807698  0.60596535]
 [-2.01816824  0.74012206  0.52881349 -0.58900053]
 [ 0.18869531 -0.75887206 -0.93323722  0.95505651]
 [ 0.19079432  1.97875732  2.60596728  0.68350889]]


In [103]:
myrandom_data1 = np.random.randn(6,4)

In [104]:
print(myrandom_data1)

[[ 3.02665449e-01  1.69372293e+00 -1.70608593e+00 -1.15911942e+00]
 [-1.34840721e-01  3.90527843e-01  1.66904636e-01  1.84501859e-01]
 [ 8.07705914e-01  7.29596753e-02  6.38787013e-01  3.29646299e-01]
 [-4.97104023e-01 -7.54069701e-01 -9.43406403e-01  4.84751647e-01]
 [-1.16773316e-01  1.90175480e+00  2.38126959e-01  1.99665229e+00]
 [-9.93263500e-01  1.96799505e-01 -1.13664459e+00  3.66479606e-04]]


In [105]:
#creating a data frame using random number generator randn
mydf = pd.DataFrame(data=myrandom_data, index = ['A','B','C','D','E'], columns=['W','X','Y','Z'])
print(mydf)
mydf1 = pd.DataFrame(data=myrandom_data, index = ['A','B','C','D','E'], columns=['salespersoname','age','location','productsold'])
print(mydf1)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509
   salespersoname       age  location  productsold
A        2.706850  0.628133  0.907969     0.503826
B        0.651118 -0.319318 -0.848077     0.605965
C       -2.018168  0.740122  0.528813    -0.589001
D        0.188695 -0.758872 -0.933237     0.955057
E        0.190794  1.978757  2.605967     0.683509


In [106]:
#CREATING A DATA FRAME FROM A LIST
df_list = [['a1','b1','c1'],['a2','b2','c2'],['a3','b3','c3']]
print(df_list)

[['a1', 'b1', 'c1'], ['a2', 'b2', 'c2'], ['a3', 'b3', 'c3']]


In [107]:
#to create user defined index, let us create a list of index
df_index = ['indx1','indx2','indx3']

In [108]:
mylist_df = pd.DataFrame(data=df_list,index=df_index,columns=('ColA','ColB','Colc'))
print(mylist_df)

      ColA ColB Colc
indx1   a1   b1   c1
indx2   a2   b2   c2
indx3   a3   b3   c3


In [109]:
df_list1 = [['a1','b1','c1'],[100,200,300],['a3',200,99.99]]
mylist_df1 = pd.DataFrame(data=df_list1,index=df_index,columns=('ColA','ColB','Colc'))

print(df_list1)
print(mylist_df1)

[['a1', 'b1', 'c1'], [100, 200, 300], ['a3', 200, 99.99]]
      ColA ColB   Colc
indx1   a1   b1     c1
indx2  100  200    300
indx3   a3  200  99.99


In [110]:
#creating dataframe from a numpy array
import numpy as np
arrtry = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arrtry)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [111]:
mylist_df3 = pd.DataFrame(data=arrtry,index=df_index,columns=('ColA','ColB','Colc'))
print(mylist_df3)

       ColA  ColB  Colc
indx1     1     2     3
indx2     4     5     6
indx3     7     8     9


In [112]:
#creating a data frame using random number generator randn,use shift + tab to understand more about data frame parameters
df0 = pd.DataFrame(data=randn(5,4),index=['A','B','C','D','E'],columns= ['W','X','Y','Z'])

In [113]:
df0

W         X         Y         Z
A  1.025984 -0.156598 -0.031579  0.649826
B  2.154846 -0.610259 -0.755325 -0.346419
C  0.147027 -0.479448  0.558769  1.024810
D -0.925874  1.862864 -1.133817  0.610478
E  0.386030  2.084019 -0.376519  0.230336

In [114]:
type(df0)

pandas.core.frame.DataFrame

In [115]:
#if index parameter is removed, row names are replaced by defauly indexes
df00 = pd.DataFrame(data=randn(5,4),columns= ['W','X','Y','Z'])
df00

W         X         Y         Z
0  0.681209  1.035125 -0.031160  1.939932
1 -1.005187 -0.741790  0.187125 -0.732845
2 -1.382920  1.482495  0.961458 -2.141212
3  0.992573  1.192241 -1.046780  1.292765
4 -1.467514 -0.494095 -0.162535  0.485809

In [116]:
#if column parameter is removed, column names are replaced by defauly indexes
df01 = pd.DataFrame(data=randn(5,4),index=['A','B','C','D','E'])
df01

0         1         2         3
A  0.392489  0.221491 -0.855196  1.541990
B  0.666319 -0.538235 -0.568581  1.407338
C  0.641806 -0.905100 -0.391157  1.028293
D -1.972605 -0.866885  0.720788 -1.223082
E  1.606780 -1.115710 -1.385379 -1.329660

In [117]:
#if both index and column parameter is removed, row and column names are replaced by defauly indexes
df02 = pd.DataFrame(data=randn(5,4))
df02

0         1         2         3
0  0.041460 -0.411055 -0.771329  0.110477
1 -0.804652  0.253548  0.649148  0.358941
2 -1.080471  0.902398  0.161781  0.833029
3  0.975720 -0.388239  0.783316 -0.708954
4  0.586847 -1.621348  0.677535  0.026105

In [118]:
#creating a data frame from a list
df_list = [['a1','b1','c1'],['a2','b2','c2'],['a3','b3','c3']]
df_list

#to create user defined index, let us create a list of index
df_index = ['indx1','indx2','indx3']


In [119]:
#create dataframe from list
#data_Frame_list = pd.DataFrame(data=df_list)

data_Frame_list = pd.DataFrame(data=df_list,index=df_index,columns=('ColA','ColB','Colc'))
data_Frame_list

ColA ColB Colc
indx1   a1   b1   c1
indx2   a2   b2   c2
indx3   a3   b3   c3

In [120]:
#creating a dataframe from dictionary
#let us create a new diction
df_dict1 = {'k1':(1,2,3),'k2':(20,30,40),'k3':(30,40,50),'k4':[100,200,300]}
df_dict1

{'k1': (1, 2, 3),
 'k2': (20, 30, 40),
 'k3': (30, 40, 50),
 'k4': [100, 200, 300]}

In [121]:
data_Frame_dict1 = pd.DataFrame(data=df_dict1,index=('I1','I2','I3','I4'),columns=('ColA','ColB','ColC','ColD'))
data_Frame_dict1

ColA ColB ColC ColD
I1  NaN  NaN  NaN  NaN
I2  NaN  NaN  NaN  NaN
I3  NaN  NaN  NaN  NaN
I4  NaN  NaN  NaN  NaN

In [122]:
data_Frame_dict1 = pd.DataFrame(data=df_dict1,index=('I1','I2','I3'),columns=('k1','k2'))
data_Frame_dict1

k1  k2
I1   1  20
I2   2  30
I3   3  40

In [123]:
data_Frame_dict1 = pd.DataFrame(data=df_dict1,index=('I1','I2','I3'),columns=('k1','k2','k3','k4'))
data_Frame_dict1

k1  k2  k3   k4
I1   1  20  30  100
I2   2  30  40  200
I3   3  40  50  300

In [124]:
#default creation of dataframe using a dictionary
#keys of the dictionary will be sitting as columns
data_Frame_dict1 = pd.DataFrame(data=df_dict1)
print(data_Frame_dict1)

   k1  k2  k3   k4
0   1  20  30  100
1   2  30  40  200
2   3  40  50  300
